[package]
name = "project_g"
version = "0.3.0"
authors = ["Mee"]
edition = "2021"
description = "A simple asynchronous server/client crate built on tokio for easy two-way streaming."
homepage = "forgor"
repository = "forgor"
license = "forgor"
keywords = ["netcode", "async", "server"]
categories = ["forgor"]
include = ["/src", "README.md"]
publish = false

[lib]

[[example]]
name = "server"
required-features = ["server"]

[[example]]
name="minimal_server"
required-features = ["server"]

[[example]]
name="minimal_client"
required-features = ["client"]

[[test]]
name="basic"
required-features = ["server", "client"]

[[test]]
name="many_clients"
required-features = ["server", "client"]

[features]
default = ["server", "client"]
client = []
server = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tokio = { version = "1.20", features = ["macros", "net", "rt-multi-thread", "sync"] }
async-recursion = "1.0"
